--
-- PostgreSQL database dump
--

\restrict 3sLUq0VLI279SYuPhn6fwg5ejCDDE1uqgYSToRaR2TIXgc9YEaCNR80S8fyefL9

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: lms_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO lms_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: lms_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: lms_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO lms_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: lms_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: lms_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO lms_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: lms_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: lms_user
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO lms_user;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: lms_user
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO lms_user;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: lms_user
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: lms_user
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: lms_user
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO lms_user;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: lms_user
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: lms_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO lms_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: lms_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: lms_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO lms_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: lms_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: lms_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO lms_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: lms_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: lms_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO lms_user;

--
-- Name: mentors_mentor; Type: TABLE; Schema: public; Owner: lms_user
--

CREATE TABLE public.mentors_mentor (
    mentor_id character varying(10) NOT NULL,
    mentor_email character varying(254) NOT NULL,
    mentor_expertise character varying(100),
    mentor_name character varying(25)
);


ALTER TABLE public.mentors_mentor OWNER TO lms_user;

--
-- Name: students_student; Type: TABLE; Schema: public; Owner: lms_user
--

CREATE TABLE public.students_student (
    student_id integer NOT NULL,
    name character varying(25) NOT NULL,
    branch character varying(20) NOT NULL,
    mentor_id character varying(10)
);


ALTER TABLE public.students_student OWNER TO lms_user;

--
-- Name: teachers_teacher; Type: TABLE; Schema: public; Owner: lms_user
--

CREATE TABLE public.teachers_teacher (
    id bigint NOT NULL,
    teacher_id character varying(10) NOT NULL,
    name character varying(50) NOT NULL,
    email character varying(254) NOT NULL
);


ALTER TABLE public.teachers_teacher OWNER TO lms_user;

--
-- Name: teachers_teacher_id_seq; Type: SEQUENCE; Schema: public; Owner: lms_user
--

ALTER TABLE public.teachers_teacher ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teachers_teacher_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: lms_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: lms_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: lms_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add teacher	7	add_teacher
26	Can change teacher	7	change_teacher
27	Can delete teacher	7	delete_teacher
28	Can view teacher	7	view_teacher
29	Can add student	8	add_student
30	Can change student	8	change_student
31	Can delete student	8	delete_student
32	Can view student	8	view_student
33	Can add mentor	9	add_mentor
34	Can change mentor	9	change_mentor
35	Can delete mentor	9	delete_mentor
36	Can view mentor	9	view_mentor
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: lms_user
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1200000$AZOX2czEr35T0pZ0VdaZEl$bFSlgIce7gm1kqOT8AkrWzulSHD3M3BSfFWIdxkjFyU=	2026-03-16 19:52:09.536+05:30	t	admin			test@gmail.com	t	t	2026-02-18 10:08:45.699+05:30
3	pbkdf2_sha256$1200000$XpbWdW4HX9tS9m7gLZ5Oy1$B0UOQWNlp/pZl/rWEcW2VQD94nlFNqY8C0u7uzriqGo=	\N	f	test123			test123@gmail.com	f	t	2026-02-26 10:49:22.082+05:30
4	test@123	\N	f	test12345			test12345@example.com	f	t	2026-03-11 19:43:19.032+05:30
5	test@1234	\N	f	john			john@example.com	f	t	2026-03-13 20:13:11.645+05:30
6	Test@1234	\N	f	jill			johnkhj@example.com	f	t	2026-03-13 20:52:11.821+05:30
8	Tet@1234	\N	f	jack			jack@example.com	f	t	2026-03-16 19:11:28.093+05:30
9	Test@123	\N	f	mark			mark@example.com	f	t	2026-03-16 19:20:55.538+05:30
10	Test@123	\N	f	mark123			mark123@example.com	f	t	2026-03-16 19:23:46.45+05:30
11	Test@123	\N	f	mark1234			mark1234@example.com	f	t	2026-03-16 19:29:27.387+05:30
12	Test@123	\N	f	mark12345			mark12345@example.com	f	t	2026-03-16 19:31:48.163+05:30
13	Test@1234	\N	f	test123455			test123455@example.com	f	t	2026-03-16 19:49:22.587+05:30
14	Test@123	\N	f	rishabh			rishabh@gmail.com	f	t	2026-03-18 07:46:22.488+05:30
15	pbkdf2_sha256$1200000$9EmAVYIsUXg4Gda3W34Wq8$cVUGhssO1QHeHrZVw6dcW6dzhO71+UIy5QhuBWXW2RI=	2026-04-13 16:23:13.072737+05:30	t	admin1			shanmukhraj2997@gmail.com	t	t	2026-04-13 16:22:57.399249+05:30
7	pbkdf2_sha256$1200000$2nEOB9F5cd579f6rqGWYcH$XHPQZtTCTrnHLuXDdwMxT8C/7kSE526ivcGUGRcqq9M=	\N	f	alice			alice@example.com	f	t	2026-03-13 20:53:51.422+05:30
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: lms_user
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: lms_user
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: lms_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-04-13 16:24:27.569485+05:30	7	alice	2	[{"changed": {"fields": ["password"]}}]	4	15
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: lms_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	teachers	teacher
8	students	student
9	mentors	mentor
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: lms_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-04-13 16:04:48.320631+05:30
2	auth	0001_initial	2026-04-13 16:04:48.382828+05:30
3	admin	0001_initial	2026-04-13 16:04:48.397717+05:30
4	admin	0002_logentry_remove_auto_add	2026-04-13 16:04:48.402746+05:30
5	admin	0003_logentry_add_action_flag_choices	2026-04-13 16:04:48.40723+05:30
6	contenttypes	0002_remove_content_type_name	2026-04-13 16:04:48.416773+05:30
7	auth	0002_alter_permission_name_max_length	2026-04-13 16:04:48.422662+05:30
8	auth	0003_alter_user_email_max_length	2026-04-13 16:04:48.427131+05:30
9	auth	0004_alter_user_username_opts	2026-04-13 16:04:48.431942+05:30
10	auth	0005_alter_user_last_login_null	2026-04-13 16:04:48.437293+05:30
11	auth	0006_require_contenttypes_0002	2026-04-13 16:04:48.438117+05:30
12	auth	0007_alter_validators_add_error_messages	2026-04-13 16:04:48.442441+05:30
13	auth	0008_alter_user_username_max_length	2026-04-13 16:04:48.449503+05:30
14	auth	0009_alter_user_last_name_max_length	2026-04-13 16:04:48.454715+05:30
15	auth	0010_alter_group_name_max_length	2026-04-13 16:04:48.460244+05:30
16	auth	0011_update_proxy_permissions	2026-04-13 16:04:48.464085+05:30
17	auth	0012_alter_user_first_name_max_length	2026-04-13 16:04:48.469541+05:30
18	mentors	0001_initial	2026-04-13 16:04:48.473744+05:30
19	mentors	0002_alter_mentor_mentor_id	2026-04-13 16:04:48.477075+05:30
20	mentors	0003_mentor_mentor_expertise	2026-04-13 16:04:48.478501+05:30
21	mentors	0004_remove_mentor_name_mentor_mentor_name_and_more	2026-04-13 16:04:48.488954+05:30
22	sessions	0001_initial	2026-04-13 16:04:48.497296+05:30
23	students	0001_initial	2026-04-13 16:04:48.503904+05:30
24	students	0002_alter_student_branch_alter_student_name	2026-04-13 16:04:48.511447+05:30
25	teachers	0001_initial	2026-04-13 16:04:48.516304+05:30
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: lms_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
lopsioutaxvjuq3pbge9hbnssrih4r92	.eJxVjDsOwyAQRO9CHSE-xiwp0_sMaFkgOImwZOwqyt2DJReJppv3Zt7M474Vv7e0-jmyK5OGXX7LgPRM9SDxgfW-cFrqts6BHwo_aePTEtPrdrp_BwVb6WuDFrUiwkEqBNmj1SDJ5ATa0ehiBpDkwIxgsgCRRe6GRmtDICWRfb7xtTd8:1wCEvz:fnYcTbMmK1fwA52kmS5L2oX_6rOJFkF1hyYkcG5F9Wg	2026-04-27 16:24:27.585112+05:30
\.


--
-- Data for Name: mentors_mentor; Type: TABLE DATA; Schema: public; Owner: lms_user
--

COPY public.mentors_mentor (mentor_id, mentor_email, mentor_expertise, mentor_name) FROM stdin;
M104539	chris@example.com	\N	Chris Woakes
M35336	mark@example.com	\N	Mark Wood
M353369	darren@example.com	\N	Darren Gough
M35337	virat@example.com	Python, Django, React	VIrat Kohli
M35340	joe@example.com	\N	Joe Root
\.


--
-- Data for Name: students_student; Type: TABLE DATA; Schema: public; Owner: lms_user
--

COPY public.students_student (student_id, name, branch, mentor_id) FROM stdin;
1001	Rohit Kumar	CSE	M35336
1003	Shivam	Agriculture	M35336
1004	Pranika kumari	CSE ML & AI	M104539
1009	Dev Krishna	CSE Data Science	\N
1010	Vicky	CSE	\N
1111	Nitin	CSE	M104539
\.


--
-- Data for Name: teachers_teacher; Type: TABLE DATA; Schema: public; Owner: lms_user
--

COPY public.teachers_teacher (id, teacher_id, name, email) FROM stdin;
1	T12345	John Cena	john@example.com
3	T22222	Alice	alice@example.com
4	T101010	Ross Gellar	ross@example.com
5	T98765	Monica Gellar	monica@example.com
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lms_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lms_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lms_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 36, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lms_user
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lms_user
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 15, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lms_user
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lms_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lms_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 9, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lms_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 25, true);


--
-- Name: teachers_teacher_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lms_user
--

SELECT pg_catalog.setval('public.teachers_teacher_id_seq', 5, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: lms_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: lms_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: lms_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: lms_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: lms_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: lms_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: lms_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: lms_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: lms_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: lms_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: lms_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: lms_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: lms_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: lms_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: lms_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: lms_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: lms_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: mentors_mentor mentors_mentor_pkey; Type: CONSTRAINT; Schema: public; Owner: lms_user
--

ALTER TABLE ONLY public.mentors_mentor
    ADD CONSTRAINT mentors_mentor_pkey PRIMARY KEY (mentor_id);


--
-- Name: students_student students_student_pkey; Type: CONSTRAINT; Schema: public; Owner: lms_user
--

ALTER TABLE ONLY public.students_student
    ADD CONSTRAINT students_student_pkey PRIMARY KEY (student_id);


--
-- Name: teachers_teacher teachers_teacher_pkey; Type: CONSTRAINT; Schema: public; Owner: lms_user
--

ALTER TABLE ONLY public.teachers_teacher
    ADD CONSTRAINT teachers_teacher_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: lms_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: lms_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: lms_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: lms_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: lms_user
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: lms_user
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: lms_user
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: lms_user
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: lms_user
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: lms_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: lms_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: lms_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: lms_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: mentors_mentor_mentor_id_2d6cc3a7_like; Type: INDEX; Schema: public; Owner: lms_user
--

CREATE INDEX mentors_mentor_mentor_id_2d6cc3a7_like ON public.mentors_mentor USING btree (mentor_id varchar_pattern_ops);


--
-- Name: students_student_mentor_id_f8845820; Type: INDEX; Schema: public; Owner: lms_user
--

CREATE INDEX students_student_mentor_id_f8845820 ON public.students_student USING btree (mentor_id);


--
-- Name: students_student_mentor_id_f8845820_like; Type: INDEX; Schema: public; Owner: lms_user
--

CREATE INDEX students_student_mentor_id_f8845820_like ON public.students_student USING btree (mentor_id varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: lms_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: lms_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: lms_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: lms_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: lms_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: lms_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: lms_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: lms_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: lms_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: students_student students_student_mentor_id_f8845820_fk_mentors_mentor_mentor_id; Type: FK CONSTRAINT; Schema: public; Owner: lms_user
--

ALTER TABLE ONLY public.students_student
    ADD CONSTRAINT students_student_mentor_id_f8845820_fk_mentors_mentor_mentor_id FOREIGN KEY (mentor_id) REFERENCES public.mentors_mentor(mentor_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO lms_user;


--
-- PostgreSQL database dump complete
--

\unrestrict 3sLUq0VLI279SYuPhn6fwg5ejCDDE1uqgYSToRaR2TIXgc9YEaCNR80S8fyefL9

