# Generated by Django 6.0.2 on 2026-02-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='mentor_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
