# Generated by Django 6.0.2 on 2026-02-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_alter_mentor_mentor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='mentor_expertise',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
