# Generated by Django 6.0.3 on 2026-03-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0003_mentor_mentor_expertise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='name',
        ),
        migrations.AddField(
            model_name='mentor',
            name='mentor_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='mentor_expertise',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='mentor_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
